version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports: 
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  # cache:
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   ports:
  #     - 8082:8081