-- Active: 1665664723648@@127.0.0.1@3306@cours_SQL


CREATE DATABASE school ;

USE school ;

CREATE TABLE promotion (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nom VARCHAR(255) NOT NULL

);
CREATE TABLE groupe (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nom VARCHAR(255) NOT NULL,
  promotion INTEGER NOT NULL
);

CREATE TABLE eleves (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nom VARCHAR(255) NOT NULL,
  prenom VARCHAR(255) NOT NULL,
  promotion INTEGER NOT NULL,
  groupe INTEGER NOT NULL
);

CREATE TABLE enseignants (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nom VARCHAR(255) NOT NULL,
  prenom VARCHAR(255) NOT NULL,
  promotion INTEGER NOT NULL
);
CREATE TABLE matiere(
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nom VARCHAR(255) NOT NULL
);
CREATE TABLE note(
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  note INTEGER NOT NULL,
  eleve INTEGER NOT NULL,
  matiere INTEGER NOT NULL,
  epreuve INTEGER NOT NULL
);
CREATE TABLE cours (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  date_time DATETIME NOT NULL,
  matiere INTEGER NOT NULL,
  duree INTEGER NOT NULL,
  groupe INTEGER NULL,
  promotion INTEGER NULL,
  enseignant INTEGER NOT NULL 
);
CREATE TABLE planning (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  année INTEGER NOT NULL,
  eleves INTEGER NOT NULL
);

CREATE TABLE epreuve (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  date_time DATETIME NOT NULL,
  duree INTEGER NOT NULL,
  promotion INTEGER NOT NULL,
  groupe INTEGER NOT NULL,
  matiere VARCHAR(255) NOT NULL
);


ALTER TABLE `eleves` ADD CONSTRAINT `eleve_promotion` FOREIGN KEY (`promotion`) REFERENCES `promotion`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `eleves` ADD CONSTRAINT `eleve_groupe` FOREIGN KEY (`groupe`) REFERENCES `groupe`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `cours` ADD CONSTRAINT `cours_groupe` FOREIGN KEY (`groupe`) REFERENCES `groupe`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `cours` ADD CONSTRAINT `cours_promotion` FOREIGN KEY (`promotion`) REFERENCES `promotion`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `cours` ADD CONSTRAINT `cours_enseignant` FOREIGN KEY (`enseignant`) REFERENCES `enseignants`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `planning` ADD CONSTRAINT `planning_eleve` FOREIGN KEY (`eleves`) REFERENCES `eleves`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `groupe` ADD CONSTRAINT `groupe_promotion` FOREIGN KEY (`promotion`) REFERENCES `promotion`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `epreuve` ADD CONSTRAINT `epreuve_promotion` FOREIGN KEY (`promotion`) REFERENCES `promotion`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `epreuve` ADD CONSTRAINT `epreuve_groupe` FOREIGN KEY (`groupe`) REFERENCES `groupe`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `note` ADD CONSTRAINT `note_eleve` FOREIGN KEY (`eleve`) REFERENCES `eleves`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `note` ADD CONSTRAINT `note_matiere` FOREIGN KEY (`matiere`) REFERENCES `matiere`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `note` ADD CONSTRAINT `note_epreuve` FOREIGN KEY (`epreuve`) REFERENCES `epreuve`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;