insert into promotion (nom) values ('Triticum aestivum, Alfalfa, Fucus vesiculosus, Laminaria digitata, Nasturtium aquaticum, Oryza sativa, Raphanus sativus, Symphytum officinale, Hordeum vulgare, Asparagus officinalis, Manganum gluconat');
insert into promotion (nom) values ('zolpidem tartrate');
insert into promotion (nom) values ('Spearmint');
insert into promotion (nom) values ('Oyster');
insert into promotion (nom) values ('Metoclopramide');
insert into promotion (nom) values ('Lamotrigine');
insert into promotion (nom) values ('Glycerin, Dimethicone');
insert into promotion (nom) values ('Levetiracetam');
insert into promotion (nom) values ('METFORMIN HYDROCHLORIDE');
insert into promotion (nom) values ('Bethanechol Chloride');
insert into promotion (nom) values ('Guaifenesin');
insert into promotion (nom) values ('tizanidine hydrochloride');
insert into promotion (nom) values ('VORICONAZOLE');
insert into promotion (nom) values ('Mesquite');
insert into promotion (nom) values ('Ibuprofen');
insert into promotion (nom) values ('Dextromethophan Hydrobromide, Chlorpheniramine Maleate, Phenylephrine Hydrochloride');
insert into promotion (nom) values ('rifampin, isoniazid and pyrazinamide');
insert into promotion (nom) values ('Betamethasone Valerate');
insert into promotion (nom) values ('Duloxetine hydrochloride');
insert into promotion (nom) values ('Montelukast Sodium');
insert into promotion (nom) values ('morphine sulfate');
insert into promotion (nom) values ('American Beech');
insert into promotion (nom) values ('Titanium Dioxide, Ethylhexyl Methoxycinnamate, Ethylhexyl Salicylate, Zinc Oxide');
insert into promotion (nom) values ('afatinib');
insert into promotion (nom) values ('hydrocodone polistirex and chlorpheniramine polistirex');
insert into promotion (nom) values ('Virginia Live Oak');
insert into promotion (nom) values ('Naltrexone Hydrochloride');
insert into promotion (nom) values ('Oxymetazoline HCl');
insert into promotion (nom) values ('Phenylephrine Hydrochloride');
insert into promotion (nom) values ('OCTINOXATE, TITANIUM DIOXIDE, and ZINC OXIDE');
insert into promotion (nom) values ('Calc phos, Kali sulph, Nat sulphuricum');
insert into promotion (nom) values ('dextromethorphan polistirex');
insert into promotion (nom) values ('ibuprofen');
insert into promotion (nom) values ('CAPTORPIL');
insert into promotion (nom) values ('Naproxen');
insert into promotion (nom) values ('Acetaminophen and Phenyltoloxamine Citrate');
insert into promotion (nom) values ('ziprasidone hydrochloride');
insert into promotion (nom) values ('arrhenatherum elatius pollen');
insert into promotion (nom) values ('levetiracetam');
insert into promotion (nom) values ('BENZALKONIUM CHLORIDE');
insert into promotion (nom) values ('hydroxyzine hydrochloride');
insert into promotion (nom) values ('Acetaminophen, Dextromethorphan HBr, Doxylamine Succinate, Pseudoephedrine HCl');
insert into promotion (nom) values ('Octinoxate and Titanium dioxide');
insert into promotion (nom) values ('Salix discolor');
insert into promotion (nom) values ('Doxycycline Hyclate');
insert into promotion (nom) values ('valsartan');
insert into promotion (nom) values ('oxycodone hydrochloride');
insert into promotion (nom) values ('barium sulfate');
insert into promotion (nom) values ('Ranitidine');
insert into promotion (nom) values ('Desipramine Hydrochloride');
insert into promotion (nom) values ('Aspirin');
insert into promotion (nom) values ('Aspirin');
insert into promotion (nom) values ('Trazodone Hydrochloride');
insert into promotion (nom) values ('Raspberry');
insert into promotion (nom) values ('Sennosides');
insert into promotion (nom) values ('salicylic acid');
insert into promotion (nom) values ('Oxcarbazepine');
insert into promotion (nom) values ('Avobenzone,Homosalate,Octisalate,Octocrylene');
insert into promotion (nom) values ('everolimus');
insert into promotion (nom) values ('Shrimp');
insert into promotion (nom) values ('Sulfamethoxazole and Trimethoprim');
insert into promotion (nom) values ('Sennosides and Sodium Dioctylsulfosuccinate');
insert into promotion (nom) values ('Famotidine');
insert into promotion (nom) values ('Oxygen');
insert into promotion (nom) values ('Metoprolol Succinate');
insert into promotion (nom) values ('ADENOSINE');
insert into promotion (nom) values ('Ipratropium Bromide');
insert into promotion (nom) values ('Tioconazole');
insert into promotion (nom) values ('Rhododendron chrysanthum, Ruta graveolens, Arnica montana, Colchicum autumnale, Phytolacca decandra, Urtica urens,');
insert into promotion (nom) values ('OCTINOXATE, TITANIUM DIOXIDE, ZINC OXIDE');
insert into promotion (nom) values ('Normal Saline with Phenol');
insert into promotion (nom) values ('PROTHROMBIN, COAGULATION FACTOR VII HUMAN, COAGULATION FACTOR IX HUMAN, COAGULATION FACTOR X HUMAN, Protein C, Protein S Human, and Water');
insert into promotion (nom) values ('ALCOHOL');
insert into promotion (nom) values ('Acetaminophen');
insert into promotion (nom) values ('CALENDULA OFFICINALIS FLOWERING TOP');
insert into promotion (nom) values ('Metoprolol tartrate');
insert into promotion (nom) values ('CHELIDONIUM MAJUS');
insert into promotion (nom) values ('Permethrin');
insert into promotion (nom) values ('oxacillin');
insert into promotion (nom) values ('Titanium Dioxide');
insert into promotion (nom) values ('Magnesium hydroxide');
insert into promotion (nom) values ('CALCIUM');
insert into promotion (nom) values ('Acetaminophen, guaifenesin, phenylephrine HCl');
insert into promotion (nom) values ('HEPARIN SODIUM');
insert into promotion (nom) values ('IBUPROFEN');
insert into promotion (nom) values ('Mushroom Agaricus spp');
insert into promotion (nom) values ('Levothyroxine Sodium');
insert into promotion (nom) values ('Quinapril Hydrochloride and Hydrochlorothiazide');
insert into promotion (nom) values ('Lidocaine');
insert into promotion (nom) values ('OCTINOXATE and OCTOCRYLENE');
insert into promotion (nom) values ('doxycycline');
insert into promotion (nom) values ('HOMOSALATE, OXYBENZONE, OCTISALATE, AVOBENZONE, OCTOCRYLENE');
insert into promotion (nom) values ('Amoxicillin');
insert into promotion (nom) values ('Carvedilol');
insert into promotion (nom) values ('OCTINOXATE AND AVOBENZONE');
insert into promotion (nom) values ('Hydroxyzine Hydrochloride');
insert into promotion (nom) values ('Duloxetine hydrochloride');
insert into promotion (nom) values ('Duloxetine hydrochloride');
insert into promotion (nom) values ('Galantamine hydrobromide');
insert into promotion (nom) values ('Pigweed Spiny');