insert into groupe (nom, promotion) values ('180 Degree Capital Corp.', 2);
insert into groupe (nom, promotion) values ('Comcast Corporation', 2);
insert into groupe (nom, promotion) values ('Q2 Holdings, Inc.', 7);
insert into groupe (nom, promotion) values ('Nuveen New Jersey Quality Municipal Income Fund', 4);
insert into groupe (nom, promotion) values ('Avista Healthcare Public Acquisition Corp.', 5);
insert into groupe (nom, promotion) values ('Grupo Financiero Galicia S.A.', 6);
insert into groupe (nom, promotion) values ('EXCO Resources NL', 7);
insert into groupe (nom, promotion) values ('Schnitzer Steel Industries, Inc.', 6);
insert into groupe (nom, promotion) values ('Nathan''s Famous, Inc.', 7);
insert into groupe (nom, promotion) values ('NiSource, Inc', 2);
insert into groupe (nom, promotion) values ('Pulse Biosciences, Inc', 3);
insert into groupe (nom, promotion) values ('Hospitality Properties Trust', 5);
insert into groupe (nom, promotion) values ('Aeglea BioTherapeutics, Inc.', 1);
insert into groupe (nom, promotion) values ('Unilever PLC', 5);
insert into groupe (nom, promotion) values ('Principal Shareholder Yield Index ETF', 5);
insert into groupe (nom, promotion) values ('Exelon Corporation', 6);
insert into groupe (nom, promotion) values ('Ctrip.com International, Ltd.', 1);
insert into groupe (nom, promotion) values ('First Financial Bancorp.', 2);
insert into groupe (nom, promotion) values ('Uranium Resources, Inc.', 3);
insert into groupe (nom, promotion) values ('Fortinet, Inc.', 1);
insert into groupe (nom, promotion) values ('Paramount Group, Inc.', 1);
insert into groupe (nom, promotion) values ('Washington Prime Group Inc.', 1);
insert into groupe (nom, promotion) values ('Mednax, Inc', 4);
insert into groupe (nom, promotion) values ('Waste Connections, Inc.', 6);
insert into groupe (nom, promotion) values ('Pearson, Plc', 3);
insert into groupe (nom, promotion) values ('Nortech Systems Incorporated', 3);
insert into groupe (nom, promotion) values ('MVC Capital, Inc.', 2);
insert into groupe (nom, promotion) values ('VelocityShares 3x Long Gold ETN', 4);
insert into groupe (nom, promotion) values ('Equity Residential', 5);
insert into groupe (nom, promotion) values ('ClearBridge Energy MLP Total Return Fund Inc.', 7);
insert into groupe (nom, promotion) values ('Landmark Infrastructure Partners LP', 2);
insert into groupe (nom, promotion) values ('Loxo Oncology, Inc.', 3);
insert into groupe (nom, promotion) values ('John B. Sanfilippo & Son, Inc.', 3);
insert into groupe (nom, promotion) values ('Ashford Hospitality Trust Inc', 3);
insert into groupe (nom, promotion) values ('Western Alliance Bancorporation', 5);
insert into groupe (nom, promotion) values ('CombiMatrix Corporation', 1);
insert into groupe (nom, promotion) values ('OncoMed Pharmaceuticals, Inc.', 1);
insert into groupe (nom, promotion) values ('CPB Inc.', 4);
insert into groupe (nom, promotion) values ('Adverum Biotechnologies, Inc.', 1);
insert into groupe (nom, promotion) values ('Air T, Inc.', 3);
insert into groupe (nom, promotion) values ('KKR Real Estate Finance Trust Inc.', 1);
insert into groupe (nom, promotion) values ('Biostage, Inc.', 7);
insert into groupe (nom, promotion) values ('LendingClub Corporation', 5);
insert into groupe (nom, promotion) values ('New York REIT, Inc.', 6);
insert into groupe (nom, promotion) values ('SodaStream International Ltd.', 7);
insert into groupe (nom, promotion) values ('Celgene Corporation', 5);
insert into groupe (nom, promotion) values ('ShotSpotter, Inc.', 3);
insert into groupe (nom, promotion) values ('Cameco Corporation', 6);
insert into groupe (nom, promotion) values ('Patterson Companies, Inc.', 4);
insert into groupe (nom, promotion) values ('DCP Midstream LP', 6);
insert into groupe (nom, promotion) values ('PowerShares S&P SmallCap Health Care Portfolio', 4);
insert into groupe (nom, promotion) values ('Tandem Diabetes Care, Inc.', 4);
insert into groupe (nom, promotion) values ('Fiat Chrysler Automobiles N.V.', 2);
insert into groupe (nom, promotion) values ('Resource Capital Corp.', 4);
insert into groupe (nom, promotion) values ('GP Investments Acquisition Corp.', 4);
insert into groupe (nom, promotion) values ('Utah Medical Products, Inc.', 3);
insert into groupe (nom, promotion) values ('Egalet Corporation', 7);
insert into groupe (nom, promotion) values ('American Campus Communities Inc', 2);
insert into groupe (nom, promotion) values ('Sears Holdings Corporation', 5);
insert into groupe (nom, promotion) values ('Plexus Corp.', 1);
insert into groupe (nom, promotion) values ('Athene Holding Ltd.', 6);
insert into groupe (nom, promotion) values ('MSG Networks Inc.', 2);
insert into groupe (nom, promotion) values ('Alliance Resource Partners, L.P.', 7);
insert into groupe (nom, promotion) values ('Papa John''s International, Inc.', 3);
insert into groupe (nom, promotion) values ('Electronics for Imaging, Inc.', 1);
insert into groupe (nom, promotion) values ('Eaton Vance Municipal Income Trust', 4);
insert into groupe (nom, promotion) values ('Microvision, Inc.', 6);
insert into groupe (nom, promotion) values ('iShares MSCI ACWI Index Fund', 4);
insert into groupe (nom, promotion) values ('Ethan Allen Interiors Inc.', 4);
insert into groupe (nom, promotion) values ('Equifax, Inc.', 6);
insert into groupe (nom, promotion) values ('Mack-Cali Realty Corporation', 2);
insert into groupe (nom, promotion) values ('Avinger, Inc.', 7);
insert into groupe (nom, promotion) values ('Michael Kors Holdings Limited', 6);
insert into groupe (nom, promotion) values ('Hydrogenics Corporation', 6);
insert into groupe (nom, promotion) values ('Revolution Lighting Technologies, Inc.', 6);
insert into groupe (nom, promotion) values ('Universal Electronics Inc.', 6);
insert into groupe (nom, promotion) values ('Murphy Oil Corporation', 5);
insert into groupe (nom, promotion) values ('Hailiang Education Group Inc.', 4);
insert into groupe (nom, promotion) values ('Actua Corporation', 3);
insert into groupe (nom, promotion) values ('WisdomTree United Kingdom Hedged Equity Fund', 3);
insert into groupe (nom, promotion) values ('Rowan Companies plc', 3);
insert into groupe (nom, promotion) values ('Molson Coors Brewing  Company', 4);
insert into groupe (nom, promotion) values ('PennyMac Financial Services, Inc.', 6);
insert into groupe (nom, promotion) values ('Sibanye Gold Limited', 6);
insert into groupe (nom, promotion) values ('Fibrocell Science Inc', 2);
insert into groupe (nom, promotion) values ('Valero Energy Partners LP', 7);
insert into groupe (nom, promotion) values ('Platform Specialty Products Corporation', 5);
insert into groupe (nom, promotion) values ('Fifth Street Finance Corp.', 1);
insert into groupe (nom, promotion) values ('Invesco Pennsylvania Value Municipal Income Trust', 2);
insert into groupe (nom, promotion) values ('Norfolk Souther Corporation', 3);
insert into groupe (nom, promotion) values ('Barington/Hilco Acquisition Corp.', 2);
insert into groupe (nom, promotion) values ('Eaton Vance NextShares Trust', 2);
insert into groupe (nom, promotion) values ('MGM Resorts International', 5);
insert into groupe (nom, promotion) values ('Centennial Resource Development, Inc.', 2);
insert into groupe (nom, promotion) values ('Mylan N.V.', 1);
insert into groupe (nom, promotion) values ('Ohr Pharmaceuticals, Inc.', 6);
insert into groupe (nom, promotion) values ('Danaos Corporation', 1);
insert into groupe (nom, promotion) values ('PennantPark Investment Corporation', 5);
insert into groupe (nom, promotion) values ('M III Acquisition Corp.', 1);
insert into groupe (nom, promotion) values ('Atossa Genetics Inc.', 4);